### ISSUE TITLE
Readme graph examples appear to be broken

### ISSUE THREAD

**Issue by rpocase** [threatify/arango-orm#74] opened 2020-12-02 21:38 UTC
I tried copy and pasting the examples in the README verbatim and am hitting issues. 

First, the client creation is wrong, it should be:

```
client = ArangoClient(hosts="your-host")
test_db = client.db('your-db', username='user', password='password')
```

Second, once I have this corrected, I'm hitting constraint errors. The `db.add(SpecializesIn(_from="teachers/T001", _to="subjects/ITP101", expertise_level="medium"))` statement causes `marshmallow.exceptions.ValidationError: {'_key': ['Missing data for required field.']}`. The error message is a bit too generic to be helpful for the specific problem.

**Comment by kashifpk** [comment] 2020-12-02 23:27
Thank you for pointing those out. Fixed in README. The `SpecializesIn` relation should not have defined the _key field as required as if it's not provided arango creates and assigns a value to it (which was the intended behavior in this case).

**Closed by kashifpk** 2020-12-02 23:27 UTC

**Comment by rpocase** [comment] 2020-12-03 15:25
Thanks for the quick response!
